import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { WebSocketServer } from 'ws';
import { TikTokLiveConnection, WebcastEvent } from 'tiktok-live-connector';

const require=createRequire(import.meta.url);
const { WebcastPushConnection }=require('tiktok-live-connector-legacy');
const PORT=Number(process.env.PORT||8787),ACCESS_KEY=String(process.env.CAOS_CONNECTOR_KEY||'').trim(),MAX_CLIENTS=Math.max(1,Number(process.env.CAOS_MAX_CLIENTS||25));
const __filename=fileURLToPath(import.meta.url),ROOT=path.resolve(path.dirname(__filename),'..');
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.ico':'image/x-icon'};

function currentVersion(){try{return String(JSON.parse(fs.readFileSync(path.join(ROOT,'version.json'),'utf8')).version||'0.0.0')}catch{return'0.0.0'}}
function patchSharedVersion(html){const v=currentVersion();return html.replace(/Caos Live v\d+\.\d+\.\d+/g,`Caos Live v${v}`).replace(/Caos Admin v\d+\.\d+\.\d+/g,`Caos Admin v${v}`).replace(/VERSÃO v\d+\.\d+\.\d+/g,`VERSÃO v${v}`).replace(/PAINEL v\d+\.\d+\.\d+/g,`PAINEL v${v}`).replace(/(<div class=\"version\">)v\d+\.\d+\.\d+/g,`$1v${v}`).replace(/(<div class=\"version\">PAINEL )v\d+\.\d+\.\d+/g,`$1v${v}`).replace(/const VERSION='\d+\.\d+\.\d+'/g,`const VERSION='${v}'`)}
function patchGameHtml(html){return patchSharedVersion(html)}
function patchAdminHtml(html){return patchSharedVersion(html)}

function serveFile(res,file){fs.readFile(file,(err,data)=>{if(err){res.writeHead(404,{'content-type':'text/plain; charset=utf-8','cache-control':'no-store'});return res.end('Not found')}const ext=path.extname(file).toLowerCase();let body=data;if(ext==='.html'){const html=data.toString('utf8'),name=path.basename(file);body=Buffer.from(name==='painel.html'?patchAdminHtml(html):name==='index.html'?patchGameHtml(html):patchSharedVersion(html),'utf8')}res.writeHead(200,{'content-type':MIME[ext]||'application/octet-stream','cache-control':'no-store'});res.end(body)})}
const server=http.createServer((req,res)=>{const pathname=decodeURIComponent((req.url||'/').split('?')[0]);if(pathname==='/health'){res.writeHead(200,{'content-type':'application/json','cache-control':'no-store'});return res.end(JSON.stringify({ok:true,service:'caos-cloud-connector',version:currentVersion(),clients:wss.clients.size}))}if(pathname==='/'||pathname==='/admin'||pathname==='/admin-latest'||pathname==='/painel.html')return serveFile(res,path.join(ROOT,'painel.html'));if(pathname==='/jogo')return serveFile(res,path.join(ROOT,'index.html'));const file=path.resolve(ROOT,pathname.replace(/^\/+/,''));if(!file.startsWith(ROOT)){res.writeHead(403);return res.end('Forbidden')}serveFile(res,file)});

const wss=new WebSocketServer({server});
function safeSend(ws,p){if(ws.readyState===ws.OPEN)ws.send(JSON.stringify(p))}
function dbg(ws,event,data={}){safeSend(ws,{type:'debug',event,...data,at:Date.now()})}
function deepValue(obj,keys,depth=0,seen=new Set()){if(!obj||typeof obj!=='object'||depth>5||seen.has(obj))return'';seen.add(obj);for(const k of keys){const v=obj[k];if(typeof v==='string'&&v.trim())return v.trim();if(typeof v==='number'&&Number.isFinite(v))return String(v)}for(const v of Object.values(obj)){if(v&&typeof v==='object'){const found=deepValue(v,keys,depth+1,seen);if(found)return found}}return''}
function getUser(data={}){return deepValue(data,['uniqueId','unique_id','uniqueID','userName','username','displayId','nickname','nickName'])||'viewer'}
function getComment(data={}){return deepValue(data,['comment','content','text','message','msg'])||''}
function normalizeGift(data={}){const user=getUser(data),gift=data.giftName||data.extendedGiftInfo?.name||data.gift?.name||deepValue(data,['giftName','gift_name'])||`gift-${data.giftId||'unknown'}`,count=Number(data.repeatCount||data.repeat_count||data.count||1)||1,repeatEnd=data.repeatEnd??data.repeat_end??true,giftType=Number(data.giftType??data.gift_type??data.extendedGiftInfo?.type??0)||0;return{type:'gift',user,gift,count,giftId:data.giftId||data.gift_id||null,repeatEnd,giftType}}
function isSigningPaywall(e){const s=String(e?.message||e||'').toLowerCase();return s.includes('business plan')||s.includes('fetchwebcastsignature')||(s.includes('eulerstream')&&s.includes('sign'))}
function isCurrent(s,live,gen){return s.live===live&&s.generation===gen}
async function closeLive(s){const live=s.live;s.generation++;s.live=null;s.username='';s.connecting=false;s.connected=false;s.mode='';if(!live)return;try{live.removeAllListeners?.()}catch{}try{await live.disconnect?.()}catch{}}
function emitLike(ws,data,mode){const user=getUser(data),count=Math.max(1,Number(data.likeCount||data.count||data.totalLikeCount||deepValue(data,['likeCount','like_count'])||1)||1);dbg(ws,'LIKE RECEBIDO',{user,count,mode});safeSend(ws,{type:'like',user,count,mode})}
function emitChat(ws,data,mode){const user=getUser(data),comment=getComment(data);dbg(ws,'CHAT RECEBIDO',{user,mode,comment:comment.slice(0,80)});safeSend(ws,{type:'chat',user,comment})}
function attachModern(ws,s,live,gen){const ok=()=>isCurrent(s,live,gen);live.on(WebcastEvent.GIFT,d=>{if(!ok())return;const g=normalizeGift(d);dbg(ws,'GIFT RECEBIDO',{user:g.user,count:g.count,gift:g.gift,mode:'modern'});if(g.giftType===1&&g.repeatEnd===false)return;safeSend(ws,g)});live.on(WebcastEvent.LIKE,d=>{if(ok())emitLike(ws,d,'modern')});const chatHandler=d=>{if(ok())emitChat(ws,d,'modern')};live.on(WebcastEvent.CHAT,chatHandler);if(WebcastEvent.CHAT!=='chat')live.on('chat',chatHandler);live.on('comment',chatHandler);live.on('disconnected',()=>{if(!ok())return;s.connected=false;s.connecting=false;safeSend(ws,{type:'status',status:'disconnected',sessionId:gen})});live.on('error',e=>{if(ok())dbg(ws,'ERRO TIKTOK',{detail:String(e?.message||e).slice(0,180),mode:'modern'})})}
function attachLegacy(ws,s,live,gen){const ok=()=>isCurrent(s,live,gen);live.on('gift',d=>{if(!ok())return;const g=normalizeGift(d);dbg(ws,'GIFT RECEBIDO',{user:g.user,count:g.count,gift:g.gift,mode:'legacy'});if(g.giftType===1&&g.repeatEnd===false)return;safeSend(ws,g)});live.on('like',d=>{if(ok())emitLike(ws,d,'legacy')});live.on('chat',d=>{if(ok())emitChat(ws,d,'legacy')});live.on('comment',d=>{if(ok())emitChat(ws,d,'legacy')});live.on('disconnected',()=>{if(!ok())return;s.connected=false;s.connecting=false;safeSend(ws,{type:'status',status:'disconnected',sessionId:gen})});live.on('error',e=>{if(ok())dbg(ws,'ERRO TIKTOK',{detail:String(e?.message||e).slice(0,180),mode:'legacy'})})}
async function tryLegacy(ws,s,u){const gen=++s.generation;safeSend(ws,{type:'status',status:'fallback',username:u,sessionId:gen});const live=new WebcastPushConnection(u,{processInitialData:false,fetchRoomInfoOnConnect:true,enableExtendedGiftInfo:false,enableWebsocketUpgrade:true,requestPollingIntervalMs:1000});s.live=live;s.mode='legacy';s.connected=false;attachLegacy(ws,s,live,gen);try{const info=await live.connect();if(!isCurrent(s,live,gen)){try{await live.disconnect?.()}catch{}return false}s.connecting=false;s.connected=true;safeSend(ws,{type:'status',status:'connected',username:u,roomId:info?.roomId||null,mode:'legacy',sessionId:gen,connectedAt:Date.now()});return true}catch(e){if(isCurrent(s,live,gen)){s.connecting=false;await closeLive(s);safeSend(ws,{type:'error',message:`Fallback falhou: ${String(e?.message||e).slice(0,220)}`})}return false}}
async function connectLive(ws,s,u){u=String(u||'').trim().replace(/^@/,'');if(!u)return safeSend(ws,{type:'error',message:'Informe o @usuario da LIVE.'});if(s.connected&&s.live&&s.username===u){return safeSend(ws,{type:'status',status:'connected',username:u,mode:s.mode,sessionId:s.generation,connectedAt:s.connectedAt||Date.now(),reused:true})}if(s.connecting)return;if(s.live)await closeLive(s);s.connecting=true;s.username=u;s.connected=false;const gen=++s.generation;safeSend(ws,{type:'status',status:'checking',username:u,sessionId:gen});const live=new TikTokLiveConnection(u,{enableExtendedGiftInfo:false,processInitialData:false,fetchRoomInfoOnConnect:true});s.live=live;s.mode='modern';attachModern(ws,s,live,gen);try{const info=await live.connect();if(!isCurrent(s,live,gen)){try{await live.disconnect?.()}catch{}return}s.connecting=false;s.connected=true;s.connectedAt=Date.now();safeSend(ws,{type:'status',status:'connected',username:u,roomId:info?.roomId||null,mode:'modern',sessionId:gen,connectedAt:s.connectedAt})}catch(e){try{live.removeAllListeners?.();await live.disconnect?.()}catch{}if(!isCurrent(s,live,gen))return;s.live=null;s.connected=false;if(isSigningPaywall(e))return tryLegacy(ws,s,u);s.connecting=false;safeSend(ws,{type:'error',message:String(e?.message||e).slice(0,260)})}}
wss.on('connection',ws=>{if(wss.clients.size>MAX_CLIENTS){safeSend(ws,{type:'error',message:'Servidor temporariamente lotado.'});return ws.close(1013,'busy')}const s={authenticated:!ACCESS_KEY,live:null,username:'',connecting:false,connected:false,connectedAt:0,mode:'',generation:0};safeSend(ws,{type:'bridge',status:'ready',authRequired:Boolean(ACCESS_KEY)});ws.on('message',async raw=>{let m;try{m=JSON.parse(raw.toString())}catch{return}if(m.type==='auth'){s.authenticated=!ACCESS_KEY||String(m.key||'')===ACCESS_KEY;return safeSend(ws,{type:'auth',ok:s.authenticated})}if(!s.authenticated)return safeSend(ws,{type:'error',message:'Chave do Caos Connector inválida.'});if(m.type==='connect')await connectLive(ws,s,m.username);if(m.type==='disconnect'){await closeLive(s);safeSend(ws,{type:'status',status:'disconnected',sessionId:s.generation})}if(m.type==='ping')safeSend(ws,{type:'pong',at:Date.now(),mode:s.mode,live:s.connected,sessionId:s.generation,connectedAt:s.connectedAt||0})});ws.on('close',()=>closeLive(s))});
server.listen(PORT,'0.0.0.0',()=>console.log(`CAOS CLOUD CONNECTOR v${currentVersion()} session isolation online :${PORT}`));