const fmtTime=at=>at?new Date(at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit',second:'2-digit',fractionalSecondDigits:3}):'—';
const fmtAgo=at=>{if(!at)return'—';const s=Math.max(0,Math.floor((Date.now()-at)/1000));return s<2?'agora':s<60?`há ${s}s`:s<3600?`há ${Math.floor(s/60)}min`:`há ${Math.floor(s/3600)}h`};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const liveTypes=new Set(['like','chat','gift','follow','share']);
const traceId=()=>`evt_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;
const delta=(a,b)=>a&&b?Math.max(0,b-a):null;
const ms=v=>v==null?'—':v<1000?`${Math.round(v)} ms`:`${(v/1000).toFixed(v>=10000?1:2)} s`;
const avg=list=>list.length?list.reduce((a,b)=>a+b,0)/list.length:null;
const typeLabel=t=>({chat:'COMENTÁRIO',like:'LIKE',gift:'GIFT',follow:'FOLLOW',share:'SHARE'}[t]||String(t||'EVENTO').toUpperCase());

export class LiveDiagnostics{
  constructor(client,els){
    this.client=client;this.els=els;this.entries=[];this.mode='—';this.liveStatus='AGUARDANDO';this.lastCause='nenhuma';this.reconnections=0;this.lastInteractionAt=0;this.lastInteractionType='—';this.lastPong=0;this.maxEntries=40;
    this.traces=new Map();this.traceOrder=[];this.maxTraces=300;this.maxDetailPerGroup=10;this.renderQueued=false;this.transportWrapped=false;
    this.totals=this.emptyTotals();this.mountStandalone();this.bind();this.installTransportProbe();
  }
  emptyTotals(){return{received:0,sent:0,gameReceived:0,executed:0,failed:0,likesReceived:0,likeBatches:0,likeSent:0,likeExecuted:0}}
  mountStandalone(){
    const nav=document.querySelector('.viewTabs'),footer=document.querySelector('main.shell > footer'),panel=document.getElementById('diagnosticsPanel'),toggle=document.getElementById('toggleDiagnostics');if(!nav||!footer||!panel)return;
    if(!nav.querySelector('[data-view-tab="diagnostic"]')){const b=document.createElement('button');b.className='viewTab';b.type='button';b.dataset.viewTab='diagnostic';b.textContent='DIAGNÓSTICO';nav.appendChild(b);b.addEventListener('click',()=>this.showView('diagnostic'))}
    let section=document.getElementById('diagnosticSection');if(!section){section=document.createElement('section');section.className='card cardGlow diagnosticWorkspace';section.id='diagnosticSection';section.dataset.view='diagnostic';section.hidden=true;section.innerHTML=`<div class="sectionHead"><div><div class="kicker">DIAGNÓSTICO · RASTREAMENTO</div><h2>Caminho real dos eventos</h2><p class="sectionDesc">Captura → painel → transporte → jogo → execução. Resumo leve para acompanhar carga real sem lotar a tela.</p></div><span class="badge purpleBadge" id="traceHealth">AGUARDANDO</span></div><div class="traceSummary"><div class="traceMetric"><span>RECEBIDOS</span><strong id="traceReceived">0</strong><small>acumulado da sessão</small></div><div class="traceMetric"><span>ENVIADOS</span><strong id="traceSent">0</strong><small>acumulado da sessão</small></div><div class="traceMetric"><span>JOGO RECEBEU</span><strong id="traceGameReceived">0</strong><small>ACK recebido</small></div><div class="traceMetric"><span>EXECUTADOS</span><strong id="traceExecuted">0</strong><small>ACK de execução</small></div><div class="traceMetric dangerMetric"><span>FALHAS CONFIRMADAS</span><strong id="traceLost">0</strong><small>erro explícito de envio/jogo</small></div></div><div class="traceLikes"><div><span>LIKES CAPTURADOS</span><strong id="traceLikesReceived">0</strong></div><div><span>BATCHES RECEBIDOS</span><strong id="traceLikeBatches">0</strong></div><div><span>COMANDOS GERADOS</span><strong id="traceLikeSent">0</strong></div><div><span>EXECUTADOS</span><strong id="traceLikeExecuted">0</strong></div></div><div class="tracePath"><div><b>TikTok / Connector</b><i>↓</i></div><div><b>Painel / Live Engine</b><i>↓</i></div><div><b>Relay / WebRTC</b><i>↓</i></div><div><b>Jogo</b><i>↓</i></div><div><b>Ação executada</b></div></div><div class="traceToolbar"><div><span>SAÚDE DOS COMANDOS</span><small>categorias recolhidas · detalhes só quando você abrir</small></div><button id="traceClear" class="dangerGhost" type="button">LIMPAR EVENTOS</button></div><div id="traceList" class="traceList"><div class="diagEmpty">Nenhum evento rastreado ainda.</div></div>`;footer.before(section)}
    if(toggle){toggle.hidden=true;toggle.style.display='none'}panel.hidden=false;section.appendChild(panel);document.getElementById('traceClear')?.addEventListener('click',()=>{this.traces.clear();this.traceOrder=[];this.totals=this.emptyTotals();this.renderTraces(true)});this.renderTraces(true);
  }
  showView(name){document.querySelectorAll('[data-view-tab]').forEach(b=>b.classList.toggle('active',b.dataset.viewTab===name));document.querySelectorAll('[data-view]').forEach(v=>v.hidden=v.dataset.view!==name);try{sessionStorage.setItem('liveplus-view',name)}catch{}}
  bind(){
    this.client.addEventListener('cloud',e=>{const d=e.detail||{};if(d.online&&d.authenticated)this.log('CONNECTOR AUTENTICADO','WebSocket + chave validados','ok');else if(!d.online&&d.error)this.log('ERRO DO CONNECTOR',d.error,'error');else if(!d.online&&d.code)this.log('CLOUD WEBSOCKET OSCILOU',`código ${d.code}${d.reason?' · '+d.reason:''}`,'warn');this.render()});
    this.client.addEventListener('pong',e=>{const d=e.detail||{};this.lastPong=Number(d.at)||Date.now();if(d.mode)this.mode=d.mode;if(d.reconnecting){this.liveStatus='RECUPERANDO';this.lastCause=`Auto Recovery · tentativa ${d.attempt||1}`}this.render()});
    this.client.addEventListener('status',e=>this.onStatus(e.detail||{}));this.client.addEventListener('debug',e=>this.onDebug(e.detail||{}));
    for(const type of liveTypes)this.client.addEventListener(type,e=>{const d=e.detail||{};this.lastInteractionAt=Date.now();this.lastInteractionType=type;this.recordInbound(d);this.render()});
    window.addEventListener('liveplus-game-state',e=>this.onGameState(e.detail||{}));window.addEventListener('liveplus-transport-route',e=>this.onTransportRoute(e.detail||{}));window.addEventListener('liveplus-game-disconnected',()=>this.renderTraces());
  }
  recordInbound(d){const id=String(d.traceId||traceId());d.traceId=id;const t=this.ensureTrace(id);t.type=d.type||t.type;t.user=d.user||t.user;t.comment=d.comment||t.comment;t.gift=d.gift||t.gift;t.amount=d.type==='like'?Math.max(1,Number(d.count)||1):1;t.connectorReceivedAt=Number(d.connectorReceivedAt)||t.connectorReceivedAt||0;t.connectorSentAt=Number(d.connectorSentAt)||Number(d.at)||t.connectorSentAt||0;t.panelReceivedAt=Number(d.panelReceivedAt)||t.panelReceivedAt||Date.now();if(!t.countedReceived){t.countedReceived=true;this.totals.received++;if(t.type==='like'){this.totals.likesReceived+=t.amount;this.totals.likeBatches++}}t.lastAt=Date.now();this.renderTraces()}
  ensureTrace(id){let t=this.traces.get(id);if(t)return t;t={id,type:'',user:'',comment:'',gift:'',amount:1,connectorReceivedAt:0,connectorSentAt:0,panelReceivedAt:0,commandCreatedAt:0,sentAt:0,gameReceivedAt:0,executedAt:0,receivedAckPanelAt:0,executedAckPanelAt:0,failedAckPanelAt:0,executionMs:null,transport:'—',action:'',status:'captured',error:'',lastAt:Date.now(),seenReceivedAck:false,seenExecutedAck:false,seenFailedAck:false,countedReceived:false,countedSent:false,countedGameReceived:false,countedExecuted:false,countedFailed:false};this.traces.set(id,t);this.traceOrder.unshift(id);while(this.traceOrder.length>this.maxTraces){const old=this.traceOrder.pop();this.traces.delete(old)}return t}
  installTransportProbe(){const tryWrap=()=>{const match=window.LivePlusMatch;if(!match?.send||match.__liveplusDiagnosticWrapped)return false;const original=match.send.bind(match);match.__liveplusDiagnosticWrapped=true;match.send=data=>{if(!data||typeof data!=='object'||data.type!=='command')return original(data);const ev=data.event||{},id=String(data.traceId||ev.traceId||traceId()),commandId=String(data.commandId||`cmd_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}`);data.traceId=id;data.commandId=commandId;const t=this.ensureTrace(id);t.type=ev.type||t.type;t.user=ev.user||t.user;t.comment=ev.comment||t.comment;t.gift=ev.gift||t.gift;t.amount=ev.type==='like'?Math.max(1,Number(ev.count)||1):t.amount;t.connectorReceivedAt=Number(ev.connectorReceivedAt)||t.connectorReceivedAt;t.connectorSentAt=Number(ev.connectorSentAt)||t.connectorSentAt;t.panelReceivedAt=Number(ev.panelReceivedAt)||t.panelReceivedAt||Date.now();t.commandCreatedAt=Date.now();t.action=String(data.action||'');t.transport='AGUARDANDO ROTA';t.sentAt=Date.now();if(!t.gameReceivedAt&&!t.executedAt)t.status='sending';const ok=original(data);if(!ok&&!t.gameReceivedAt&&!t.executedAt){t.status='send_failed';this.markFailed(t,'Falha de envio')}else{if(!t.gameReceivedAt&&!t.executedAt)t.status='sent';if(!t.countedSent){t.countedSent=true;this.totals.sent++;if(t.type==='like')this.totals.likeSent++}}t.lastAt=Date.now();this.renderTraces();return ok};this.transportWrapped=true;return true};if(!tryWrap()){const timer=setInterval(()=>{if(tryWrap())clearInterval(timer)},250);setTimeout(()=>clearInterval(timer),10000)}}
  markFailed(t,error=''){if(t.countedFailed)return;t.countedFailed=true;t.error=String(error||t.error||'falha');this.totals.failed++}
  clearFailed(t){if(!t.countedFailed)return;t.countedFailed=false;this.totals.failed=Math.max(0,this.totals.failed-1)}
  onTransportRoute(d){const id=String(d.traceId||'');if(!id)return;const t=this.ensureTrace(id);t.transport=d.route==='server'?'SERVER RELAY':d.route==='webrtc'?'WEBRTC':d.route==='failed'?'FALHA DE ENVIO':String(d.route||'DESCONHECIDO').toUpperCase();if(d.sentAt&&!t.sentAt)t.sentAt=Number(d.sentAt);if(d.ok===false&&!t.gameReceivedAt&&!t.executedAt){t.status='send_failed';t.failedAckPanelAt=Date.now();this.markFailed(t,'Transporte recusou o envio')}t.lastAt=Date.now();this.renderTraces()}
  onGameState(d){if(d.scope!=='diagnostic'||!d.traceId)return;const t=this.ensureTrace(String(d.traceId)),remoteAt=Number(d.at)||0,now=Date.now();t.action=String(d.action||t.action||'');t.lastAt=now;if(d.phase==='received'){this.clearFailed(t);if(!t.seenReceivedAck){t.seenReceivedAck=true;t.gameReceivedAt=t.gameReceivedAt||remoteAt||now;t.receivedAckPanelAt=now}if(!t.countedGameReceived){t.countedGameReceived=true;this.totals.gameReceived++}if(!t.executedAt)t.status='game_received'}else if(d.phase==='executed'){this.clearFailed(t);if(!t.seenExecutedAck){t.seenExecutedAck=true;t.executedAt=t.executedAt||remoteAt||now;t.executedAckPanelAt=now;t.executionMs=Number.isFinite(Number(d.executionMs))?Number(d.executionMs):t.executionMs}if(!t.countedExecuted){t.countedExecuted=true;this.totals.executed++;if(t.type==='like')this.totals.likeExecuted++}t.status='executed';t.error=''}else if(d.phase==='failed'){if(t.executedAt)return;if(!t.seenFailedAck){t.seenFailedAck=true;t.failedAckPanelAt=now;t.executionMs=Number.isFinite(Number(d.executionMs))?Number(d.executionMs):t.executionMs;t.error=String(d.error||'falha no jogo')}t.status='game_failed';this.markFailed(t,t.error)}this.renderTraces()}
  onStatus(m){if(m.mode)this.mode=m.mode;const s=m.status||'';if(s==='connected'){this.liveStatus='LIVE OK';this.lastCause=m.recovered?'sessão recuperada':'nova sessão TikTok';this.log(m.recovered?'TIKTOK RECUPERADA':'TIKTOK CONECTADA',`${this.mode}${m.username?' · @'+m.username:''}`,'ok')}else if(s==='checking'){this.liveStatus='CONECTANDO';this.lastCause=m.recovery?'tentativa de recuperação':'abrindo sessão TikTok';this.log(m.recovery?'RECOVERY TENTANDO':'CONEXÃO TIKTOK INICIADA',m.attempt?`tentativa ${m.attempt}`:'aguardando resposta','warn')}else if(s==='reconnecting'){this.liveStatus='RECUPERANDO';this.reconnections++;this.lastCause=m.reason||'queda inesperada';this.log(`RECONEXÃO #${this.reconnections}`,`${this.lastCause} · tentativa ${m.attempt||1}/${m.maxAttempts||2}`,'warn')}else if(s==='disconnected'){this.liveStatus='DESCONECTADA';this.lastCause=m.manual?'parada manualmente':m.reason||'TikTok desconectou';this.log('TIKTOK DESCONECTADA',this.lastCause,m.manual?'neutral':'error')}else if(s==='error'){this.liveStatus='FALHA';this.lastCause=m.reason||'erro TikTok';this.log('ERRO TIKTOK',this.lastCause,'error')}this.render()}
  onDebug(m){const event=String(m.event||'DEBUG').replaceAll('_',' ');if(m.mode)this.mode=m.mode;const detail=m.detail||m.reason||m.username||'';if(/RECUPERADA/i.test(event))this.lastCause='sessão recuperada';if(/FALHOU|ERROR|FAILED/i.test(event))this.lastCause=detail||event;this.log(event,detail,/FALHOU|ERROR|FAILED/i.test(event)?'error':/RECOVERY|AGENDADO/i.test(event)?'warn':'neutral',m.at);this.render()}
  log(title,detail='',tone='neutral',at=Date.now()){const last=this.entries[0];if(last&&last.title===title&&last.detail===detail&&Date.now()-last.at<700)return;this.entries.unshift({title,detail,tone,at:Number(at)||Date.now()});this.entries=this.entries.slice(0,this.maxEntries)}
  clear(){this.entries=[];this.render()}
  snapshot(){return{mode:this.mode,cloud:this.client.connected?'OK':'FECHADO',live:this.liveStatus,reconnections:this.reconnections,lastCause:this.lastCause,lastInteraction:this.lastInteractionAt?`${this.lastInteractionType} · ${fmtAgo(this.lastInteractionAt)}`:'—',heartbeat:this.lastPong?fmtTime(this.lastPong):'—'}}
  traceStatus(t){if(t.executedAt||t.status==='executed')return['ok','EXECUTADO'];if(t.status==='game_failed'&&!t.executedAt)return['error','FALHA NA EXECUÇÃO'];if(t.status==='send_failed'&&!t.gameReceivedAt&&!t.executedAt)return['error','FALHA DE ENVIO'];if(t.gameReceivedAt&&!t.executedAt)return['warn',Date.now()-(t.receivedAckPanelAt||t.sentAt)>3000?'ACK DE EXECUÇÃO PENDENTE':'JOGO RECEBEU'];if(t.sentAt&&!t.gameReceivedAt)return['warn',Date.now()-t.sentAt>3000?'ACK DE RECEBIMENTO PENDENTE':'ENVIADO'];return['warn','CAPTURADO']}
  traceTitle(t){if(t.type==='chat')return `“${String(t.comment||'').slice(0,70)||'comentário'}”`;if(t.type==='like')return `+${t.amount||1} curtidas`;if(t.type==='gift')return `${t.gift||'Presente'}`;return t.user?`@${t.user}`:'evento'}
  responseMs(t){if(!t.sentAt)return null;const end=t.executedAckPanelAt||t.failedAckPanelAt||t.receivedAckPanelAt||0;return end?Math.max(0,end-t.sentAt):null}
  compactDetail(t){const [tone,label]=this.traceStatus(t),r=this.responseMs(t);return `<div class="traceCompact ${tone}"><div><b>${esc(typeLabel(t.type))} · ${esc(this.traceTitle(t))}</b><small>${esc(t.action||'sem ação')} · ${esc(t.transport)}${t.error?` · ${esc(t.error)}`:''}</small></div><span>${esc(label)}${r!=null?` · ${esc(ms(r))}`:''}</span></div>`}
  groupSummary(tone,rows){const n=rows.length;if(tone==='ok'){const responses=rows.map(t=>this.responseMs(t)).filter(v=>v!=null),internal=rows.map(t=>t.executionMs).filter(v=>Number.isFinite(v));const r=avg(responses),i=avg(internal),quality=r==null?'sem tempo de ACK':r<150?'resposta ótima':r<500?'resposta boa':r<1500?'resposta moderada':'resposta lenta';return `${n} confirmados · ${quality}${r!=null?` · ACK médio ${ms(r)}`:''}${i!=null?` · execução ${i.toFixed(2)} ms`:''}`}
    if(tone==='warn'){const noReceive=rows.filter(t=>t.sentAt&&!t.gameReceivedAt).length,noExec=rows.filter(t=>t.gameReceivedAt&&!t.executedAt).length,captured=rows.filter(t=>!t.sentAt).length;return `${n} inconclusivos${noReceive?` · ${noReceive} sem ACK de recebimento`:''}${noExec?` · ${noExec} sem ACK de execução`:''}${captured?` · ${captured} ainda sem envio`:''}`}
    const reasons=new Map();for(const t of rows){const reason=t.status==='send_failed'?(t.error||'Falha de envio'):(t.error||'Falha na execução');reasons.set(reason,(reasons.get(reason)||0)+1)}const top=[...reasons.entries()].sort((a,b)=>b[1]-a[1]).slice(0,3).map(([r,c])=>`${c}× ${r}`).join(' · ');const times=rows.map(t=>this.responseMs(t)).filter(v=>v!=null),r=avg(times);return `${n} falhas confirmadas${top?` · ${top}`:''}${r!=null?` · resposta média ${ms(r)}`:''}`
  }
  errorBreakdown(rows){const map=new Map();for(const t of rows){const reason=t.status==='send_failed'?(t.error||'Falha de envio'):(t.error||'Falha na execução'),item=map.get(reason)||{count:0,times:[]};item.count++;const r=this.responseMs(t);if(r!=null)item.times.push(r);map.set(reason,item)}return [...map.entries()].sort((a,b)=>b[1].count-a[1].count).map(([reason,v])=>`<div class="traceErrorReason"><b>${v.count}× ${esc(reason)}</b><small>${v.times.length?`resposta média ${esc(ms(avg(v.times)))}`:'tempo de resposta indisponível'}</small></div>`).join('')||'<div class="diagEmpty">Nenhuma falha confirmada.</div>'}
  renderTraces(force=false){if(!force){if(this.renderQueued)return;this.renderQueued=true;setTimeout(()=>{this.renderQueued=false;this.renderTraces(true)},150);return}const list=document.getElementById('traceList');if(!list)return;const opened=new Set([...list.querySelectorAll('details.traceHealthGroup[open]')].map(el=>el.dataset.tone));const rows=this.traceOrder.map(id=>this.traces.get(id)).filter(Boolean),groups={ok:[],warn:[],error:[]};for(const t of rows){const tone=this.traceStatus(t)[0];groups[tone]?.push(t)}const set=(id,v)=>{const el=document.getElementById(id);if(el)el.textContent=String(v)};set('traceReceived',this.totals.received);set('traceSent',this.totals.sent);set('traceGameReceived',this.totals.gameReceived);set('traceExecuted',this.totals.executed);set('traceLost',this.totals.failed);set('traceLikesReceived',this.totals.likesReceived);set('traceLikeBatches',this.totals.likeBatches);set('traceLikeSent',this.totals.likeSent);set('traceLikeExecuted',this.totals.likeExecuted);const health=document.getElementById('traceHealth');if(health){health.textContent=this.totals.failed?'ATENÇÃO':groups.warn.length?'MONITORANDO':this.totals.executed?'FLUXO OK':this.totals.received?'RASTREANDO':'AGUARDANDO';health.classList.toggle('fail',!!this.totals.failed)}
    const block=(tone,title,items)=>{const details=items.slice(0,this.maxDetailPerGroup);return `<details class="traceHealthGroup ${tone}" data-tone="${tone}"${opened.has(tone)?' open':''}><summary><div><strong>${title}</strong><small>${esc(this.groupSummary(tone,items))}</small></div><span>${items.length}</span></summary><div class="traceHealthBody">${tone==='error'?`<div class="traceErrorBreakdown"><span>PRINCIPAIS ERROS</span>${this.errorBreakdown(items)}</div>`:''}<div class="traceRecentHead">ÚLTIMOS ${Math.min(details.length,this.maxDetailPerGroup)} REGISTROS</div>${details.map(t=>this.compactDetail(t)).join('')||'<div class="diagEmpty">Nenhum registro nesta categoria.</div>'}</div></details>`};
    list.innerHTML=block('ok','🟢 VERDE · EXECUTADOS',groups.ok)+block('warn','🟡 AMARELO · INCONCLUSIVOS',groups.warn)+block('error','🔴 VERMELHO · FALHAS',groups.error)}
  render(){const e=this.els;if(!e?.diagMode)return;const s=this.snapshot();e.diagMode.textContent=s.mode;e.diagCloud.textContent=s.cloud;e.diagLive.textContent=s.live;e.diagReconnects.textContent=String(s.reconnections);e.diagLastCause.textContent=s.lastCause;e.diagInteraction.textContent=s.lastInteraction;e.diagHeartbeat.textContent=s.heartbeat;e.diagLog.innerHTML=this.entries.map(x=>`<div class="diagEntry ${esc(x.tone)}"><div><b>${esc(x.title)}</b><small>${esc(x.detail||'—')}</small></div><time>${esc(fmtTime(x.at))}</time></div>`).join('')||'<div class="diagEmpty">Nenhum evento técnico registrado nesta sessão.</div>';this.renderTraces()}
}