const fmtTime=at=>at?new Date(at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit',second:'2-digit',fractionalSecondDigits:3}):'—';
const fmtAgo=at=>{if(!at)return'—';const s=Math.max(0,Math.floor((Date.now()-at)/1000));return s<2?'agora':s<60?`há ${s}s`:s<3600?`há ${Math.floor(s/60)}min`:`há ${Math.floor(s/3600)}h`};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const liveTypes=new Set(['like','chat','gift','follow','share']);
const traceId=()=>`evt_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;
const delta=(a,b)=>a&&b?Math.max(0,b-a):null;
const ms=v=>v==null?'—':v<1000?`${Math.round(v)} ms`:`${(v/1000).toFixed(v>=10000?1:2)} s`;
const typeLabel=t=>({chat:'COMENTÁRIO',like:'LIKE',gift:'GIFT',follow:'FOLLOW',share:'SHARE'}[t]||String(t||'EVENTO').toUpperCase());

export class LiveDiagnostics{
  constructor(client,els){
    this.client=client;this.els=els;this.entries=[];this.mode='—';this.liveStatus='AGUARDANDO';this.lastCause='nenhuma';this.reconnections=0;this.lastInteractionAt=0;this.lastInteractionType='—';this.lastPong=0;this.maxEntries=40;
    this.traces=new Map();this.traceOrder=[];this.maxTraces=300;this.transportWrapped=false;this.mountStandalone();this.bind();this.installTransportProbe();
  }
  mountStandalone(){
    const nav=document.querySelector('.viewTabs'),footer=document.querySelector('main.shell > footer'),panel=document.getElementById('diagnosticsPanel'),toggle=document.getElementById('toggleDiagnostics');if(!nav||!footer||!panel)return;
    if(!nav.querySelector('[data-view-tab="diagnostic"]')){const b=document.createElement('button');b.className='viewTab';b.type='button';b.dataset.viewTab='diagnostic';b.textContent='DIAGNÓSTICO';nav.appendChild(b);b.addEventListener('click',()=>this.showView('diagnostic'))}
    let section=document.getElementById('diagnosticSection');if(!section){section=document.createElement('section');section.className='card cardGlow diagnosticWorkspace';section.id='diagnosticSection';section.dataset.view='diagnostic';section.hidden=true;section.innerHTML=`<div class="sectionHead"><div><div class="kicker">DIAGNÓSTICO · RASTREAMENTO</div><h2>Caminho real dos eventos</h2><p class="sectionDesc">Captura → painel → transporte → jogo → execução. Este módulo é isolado e pode ser removido sem alterar Partida ou Live.</p></div><span class="badge purpleBadge" id="traceHealth">AGUARDANDO</span></div><div class="traceSummary"><div class="traceMetric"><span>RECEBIDOS</span><strong id="traceReceived">0</strong><small>eventos do Connector</small></div><div class="traceMetric"><span>ENVIADOS</span><strong id="traceSent">0</strong><small>comandos ao jogo</small></div><div class="traceMetric"><span>JOGO RECEBEU</span><strong id="traceGameReceived">0</strong><small>ACK recebido</small></div><div class="traceMetric"><span>EXECUTADOS</span><strong id="traceExecuted">0</strong><small>ACK de execução</small></div><div class="traceMetric dangerMetric"><span>PERDIDOS / FALHAS</span><strong id="traceLost">0</strong><small>timeout ou erro</small></div></div><div class="traceLikes"><div><span>LIKES CAPTURADOS</span><strong id="traceLikesReceived">0</strong></div><div><span>BATCHES RECEBIDOS</span><strong id="traceLikeBatches">0</strong></div><div><span>COMANDOS GERADOS</span><strong id="traceLikeSent">0</strong></div><div><span>EXECUTADOS</span><strong id="traceLikeExecuted">0</strong></div></div><div class="tracePath"><div><b>TikTok / Connector</b><i>↓</i></div><div><b>Painel / Live Engine</b><i>↓</i></div><div><b>Relay / WebRTC</b><i>↓</i></div><div><b>Jogo</b><i>↓</i></div><div><b>Ação executada</b></div></div><div class="traceToolbar"><div><span>FLUXO AO VIVO</span><small>até 300 eventos na memória</small></div><button id="traceClear" class="dangerGhost" type="button">LIMPAR EVENTOS</button></div><div id="traceList" class="traceList"><div class="diagEmpty">Nenhum evento rastreado ainda.</div></div>`;footer.before(section)}
    if(toggle){toggle.hidden=true;toggle.style.display='none'}panel.hidden=false;section.appendChild(panel);document.getElementById('traceClear')?.addEventListener('click',()=>{this.traces.clear();this.traceOrder=[];this.renderTraces()});this.renderTraces();
  }
  showView(name){document.querySelectorAll('[data-view-tab]').forEach(b=>b.classList.toggle('active',b.dataset.viewTab===name));document.querySelectorAll('[data-view]').forEach(v=>v.hidden=v.dataset.view!==name);try{sessionStorage.setItem('liveplus-view',name)}catch{}}
  bind(){
    this.client.addEventListener('cloud',e=>{const d=e.detail||{};if(d.online&&d.authenticated)this.log('CONNECTOR AUTENTICADO','WebSocket + chave validados','ok');else if(!d.online&&d.error)this.log('ERRO DO CONNECTOR',d.error,'error');else if(!d.online&&d.code)this.log('CLOUD WEBSOCKET OSCILOU',`código ${d.code}${d.reason?' · '+d.reason:''}`,'warn');this.render()});
    this.client.addEventListener('pong',e=>{const d=e.detail||{};this.lastPong=Number(d.at)||Date.now();if(d.mode)this.mode=d.mode;if(d.reconnecting){this.liveStatus='RECUPERANDO';this.lastCause=`Auto Recovery · tentativa ${d.attempt||1}`}this.render()});
    this.client.addEventListener('status',e=>this.onStatus(e.detail||{}));
    this.client.addEventListener('debug',e=>this.onDebug(e.detail||{}));
    for(const type of liveTypes)this.client.addEventListener(type,e=>{const d=e.detail||{};this.lastInteractionAt=Date.now();this.lastInteractionType=type;this.recordInbound(d);this.render()});
    window.addEventListener('liveplus-game-state',e=>this.onGameState(e.detail||{}));
    window.addEventListener('liveplus-transport-route',e=>this.onTransportRoute(e.detail||{}));
    window.addEventListener('liveplus-game-disconnected',()=>this.renderTraces());
  }
  recordInbound(d){const id=String(d.traceId||traceId());d.traceId=id;const t=this.ensureTrace(id);t.type=d.type||t.type;t.user=d.user||t.user;t.comment=d.comment||t.comment;t.gift=d.gift||t.gift;t.amount=d.type==='like'?Math.max(1,Number(d.count)||1):1;t.connectorReceivedAt=Number(d.connectorReceivedAt)||t.connectorReceivedAt||0;t.connectorSentAt=Number(d.connectorSentAt)||Number(d.at)||t.connectorSentAt||0;t.panelReceivedAt=Number(d.panelReceivedAt)||Date.now();t.lastAt=Date.now();this.renderTraces()}
  ensureTrace(id){let t=this.traces.get(id);if(t)return t;t={id,type:'',user:'',comment:'',gift:'',amount:1,connectorReceivedAt:0,connectorSentAt:0,panelReceivedAt:0,commandCreatedAt:0,sentAt:0,gameReceivedAt:0,executedAt:0,executionMs:null,transport:'—',action:'',status:'captured',lastAt:Date.now()};this.traces.set(id,t);this.traceOrder.unshift(id);while(this.traceOrder.length>this.maxTraces){const old=this.traceOrder.pop();this.traces.delete(old)}return t}
  installTransportProbe(){const tryWrap=()=>{const match=window.LivePlusMatch;if(!match?.send||match.__liveplusDiagnosticWrapped)return false;const original=match.send.bind(match);match.__liveplusDiagnosticWrapped=true;match.send=data=>{if(!data||typeof data!=='object'||data.type!=='command')return original(data);const ev=data.event||{},id=String(data.traceId||ev.traceId||traceId()),commandId=String(data.commandId||`cmd_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}`);data.traceId=id;data.commandId=commandId;const t=this.ensureTrace(id);t.type=ev.type||t.type;t.user=ev.user||t.user;t.comment=ev.comment||t.comment;t.gift=ev.gift||t.gift;t.amount=ev.type==='like'?Math.max(1,Number(ev.count)||1):t.amount;t.connectorReceivedAt=Number(ev.connectorReceivedAt)||t.connectorReceivedAt;t.connectorSentAt=Number(ev.connectorSentAt)||t.connectorSentAt;t.panelReceivedAt=Number(ev.panelReceivedAt)||t.panelReceivedAt||Date.now();t.commandCreatedAt=Date.now();t.action=String(data.action||'');t.transport='AGUARDANDO ROTA';t.status='command_created';const ok=original(data);t.sentAt=Date.now();t.status=ok?'sent':'send_failed';t.lastAt=t.sentAt;this.renderTraces();return ok};this.transportWrapped=true;return true};if(!tryWrap()){const timer=setInterval(()=>{if(tryWrap())clearInterval(timer)},250);setTimeout(()=>clearInterval(timer),10000)}}
  onTransportRoute(d){const id=String(d.traceId||'');if(!id)return;const t=this.ensureTrace(id);t.transport=d.route==='server'?'SERVER RELAY':d.route==='webrtc'?'WEBRTC':d.route==='failed'?'FALHA DE ENVIO':String(d.route||'DESCONHECIDO').toUpperCase();if(d.sentAt&&!t.sentAt)t.sentAt=Number(d.sentAt);if(d.ok===false)t.status='send_failed';t.lastAt=Date.now();this.renderTraces()}
  onGameState(d){if(d.scope!=='diagnostic'||!d.traceId)return;const t=this.ensureTrace(String(d.traceId));const at=Number(d.at)||Date.now();t.action=String(d.action||t.action||'');t.lastAt=at;if(d.phase==='received'){t.gameReceivedAt=at;t.status='game_received'}else if(d.phase==='executed'){t.executedAt=at;t.executionMs=Number.isFinite(Number(d.executionMs))?Number(d.executionMs):null;t.status='executed'}else if(d.phase==='failed'){t.executedAt=at;t.executionMs=Number.isFinite(Number(d.executionMs))?Number(d.executionMs):null;t.status='game_failed';t.error=String(d.error||'falha no jogo')}this.renderTraces()}
  onStatus(m){if(m.mode)this.mode=m.mode;const s=m.status||'';
    if(s==='connected'){this.liveStatus='LIVE OK';this.lastCause=m.recovered?'sessão recuperada':'nova sessão TikTok';this.log(m.recovered?'TIKTOK RECUPERADA':'TIKTOK CONECTADA',`${this.mode}${m.username?' · @'+m.username:''}`,'ok')}
    else if(s==='checking'){this.liveStatus='CONECTANDO';this.lastCause=m.recovery?'tentativa de recuperação':'abrindo sessão TikTok';this.log(m.recovery?'RECOVERY TENTANDO':'CONEXÃO TIKTOK INICIADA',m.attempt?`tentativa ${m.attempt}`:'aguardando resposta','warn')}
    else if(s==='reconnecting'){this.liveStatus='RECUPERANDO';this.reconnections+=1;this.lastCause=m.reason||'queda inesperada';this.log(`RECONEXÃO #${this.reconnections}`,`${this.lastCause} · tentativa ${m.attempt||1}/${m.maxAttempts||2}`,'warn')}
    else if(s==='disconnected'){this.liveStatus='DESCONECTADA';this.lastCause=m.manual?'parada manualmente':m.reason||'TikTok desconectou';this.log('TIKTOK DESCONECTADA',this.lastCause,m.manual?'neutral':'error')}
    else if(s==='error'){this.liveStatus='FALHA';this.lastCause=m.reason||'erro TikTok';this.log('ERRO TIKTOK',this.lastCause,'error')}
    this.render()}
  onDebug(m){const event=String(m.event||'DEBUG').replaceAll('_',' ');if(m.mode)this.mode=m.mode;const detail=m.detail||m.reason||m.username||'';if(/RECUPERADA/i.test(event))this.lastCause='sessão recuperada';if(/FALHOU|ERROR|FAILED/i.test(event))this.lastCause=detail||event;this.log(event,detail,/FALHOU|ERROR|FAILED/i.test(event)?'error':/RECOVERY|AGENDADO/i.test(event)?'warn':'neutral',m.at);this.render()}
  log(title,detail='',tone='neutral',at=Date.now()){const last=this.entries[0];if(last&&last.title===title&&last.detail===detail&&Date.now()-last.at<700)return;this.entries.unshift({title,detail,tone,at:Number(at)||Date.now()});this.entries=this.entries.slice(0,this.maxEntries)}
  clear(){this.entries=[];this.render()}
  snapshot(){return{mode:this.mode,cloud:this.client.connected?'OK':'FECHADO',live:this.liveStatus,reconnections:this.reconnections,lastCause:this.lastCause,lastInteraction:this.lastInteractionAt?`${this.lastInteractionType} · ${fmtAgo(this.lastInteractionAt)}`:'—',heartbeat:this.lastPong?fmtTime(this.lastPong):'—'}}
  traceStatus(t){if(t.status==='executed')return['ok','EXECUTADO'];if(['send_failed','game_failed'].includes(t.status))return['error','FALHOU'];if(t.sentAt&&!t.gameReceivedAt&&Date.now()-t.sentAt>3000)return['error','SEM ACK DO JOGO'];if(t.gameReceivedAt&&!t.executedAt&&Date.now()-t.gameReceivedAt>3000)return['warn','RECEBIDO · SEM EXECUÇÃO'];if(t.gameReceivedAt)return['ok','JOGO RECEBEU'];if(t.sentAt)return['warn','ENVIADO'];return['neutral','CAPTURADO']}
  traceTitle(t){if(t.type==='chat')return `“${String(t.comment||'').slice(0,70)||'comentário'}”`;if(t.type==='like')return `+${t.amount||1} curtidas`;if(t.type==='gift')return `${t.gift||'Presente'}`;return t.user?`@${t.user}`:'evento'}
  renderTraces(){const list=document.getElementById('traceList');if(!list)return;const rows=this.traceOrder.map(id=>this.traces.get(id)).filter(Boolean),received=rows.filter(t=>t.panelReceivedAt).length,sent=rows.filter(t=>t.sentAt&&t.status!=='send_failed').length,gameReceived=rows.filter(t=>t.gameReceivedAt).length,executed=rows.filter(t=>t.status==='executed').length,lost=rows.filter(t=>['send_failed','game_failed'].includes(t.status)||(t.sentAt&&!t.gameReceivedAt&&Date.now()-t.sentAt>3000)).length,likes=rows.filter(t=>t.type==='like'),likesReceived=likes.reduce((n,t)=>n+(t.amount||1),0),likeSent=likes.filter(t=>t.sentAt&&t.status!=='send_failed').length,likeExec=likes.filter(t=>t.status==='executed').length;
    const set=(id,v)=>{const el=document.getElementById(id);if(el)el.textContent=String(v)};set('traceReceived',received);set('traceSent',sent);set('traceGameReceived',gameReceived);set('traceExecuted',executed);set('traceLost',lost);set('traceLikesReceived',likesReceived);set('traceLikeBatches',likes.length);set('traceLikeSent',likeSent);set('traceLikeExecuted',likeExec);const health=document.getElementById('traceHealth');if(health){health.textContent=lost?'ATENÇÃO':executed?'FLUXO OK':received?'RASTREANDO':'AGUARDANDO';health.classList.toggle('fail',!!lost)}
    list.innerHTML=rows.slice(0,120).map(t=>{const [tone,label]=this.traceStatus(t),connectorQueue=delta(t.connectorReceivedAt,t.connectorSentAt),toPanel=delta(t.connectorSentAt,t.panelReceivedAt),toSend=delta(t.panelReceivedAt,t.sentAt),toGame=delta(t.sentAt,t.gameReceivedAt),exec=delta(t.gameReceivedAt,t.executedAt),total=delta(t.connectorReceivedAt||t.panelReceivedAt,t.executedAt||t.gameReceivedAt||t.sentAt||t.panelReceivedAt);return `<article class="traceEvent ${tone}"><div class="traceEventHead"><div><span>${esc(typeLabel(t.type))}</span><strong>${esc(this.traceTitle(t))}</strong><small>${esc(t.action?`ação: ${t.action}`:'sem comando gerado ainda')}</small></div><b>${esc(label)}</b></div><div class="traceTimeline"><div><span>Connector recebeu</span><strong>${esc(fmtTime(t.connectorReceivedAt))}</strong><small>fila ${esc(ms(connectorQueue))}</small></div><div><span>Painel recebeu</span><strong>${esc(fmtTime(t.panelReceivedAt))}</strong><small>rede ${esc(ms(toPanel))}</small></div><div><span>Enviado ao jogo</span><strong>${esc(fmtTime(t.sentAt))}</strong><small>${esc(t.transport)} · ${esc(ms(toSend))}</small></div><div><span>Jogo recebeu</span><strong>${esc(fmtTime(t.gameReceivedAt))}</strong><small>${esc(ms(toGame))}</small></div><div><span>Executou</span><strong>${esc(fmtTime(t.executedAt))}</strong><small>${esc(t.executionMs!=null?`${t.executionMs.toFixed(2)} ms interno`:ms(exec))}</small></div></div><div class="traceTotal"><span>${esc(t.id)}</span><strong>TOTAL ${esc(ms(total))}</strong></div></article>`}).join('')||'<div class="diagEmpty">Nenhum evento rastreado ainda.</div>'}
  render(){const e=this.els;if(!e?.diagMode)return;const s=this.snapshot();e.diagMode.textContent=s.mode;e.diagCloud.textContent=s.cloud;e.diagLive.textContent=s.live;e.diagReconnects.textContent=String(s.reconnections);e.diagLastCause.textContent=s.lastCause;e.diagInteraction.textContent=s.lastInteraction;e.diagHeartbeat.textContent=s.heartbeat;e.diagLog.innerHTML=this.entries.map(x=>`<div class="diagEntry ${esc(x.tone)}"><div><b>${esc(x.title)}</b><small>${esc(x.detail||'—')}</small></div><time>${esc(fmtTime(x.at))}</time></div>`).join('')||'<div class="diagEmpty">Nenhum evento técnico registrado nesta sessão.</div>';this.renderTraces()}
}
