const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

const cleanOptions=options=>(Array.isArray(options)?options:[]).map(o=>typeof o==='string'?{value:o,label:o}:{value:String(o?.value??o?.id??''),label:String(o?.label??o?.name??o?.value??'')}).filter(o=>o.value&&o.label);
const cleanField=(raw,index)=>{const type=['number','select','text','toggle'].includes(raw?.type)?raw.type:'text';return{id:String(raw?.id||`param${index+1}`),label:String(raw?.label||raw?.name||`Parâmetro ${index+1}`),type,required:raw?.required!==false,min:Number.isFinite(Number(raw?.min))?Number(raw.min):undefined,max:Number.isFinite(Number(raw?.max))?Number(raw.max):undefined,step:Number.isFinite(Number(raw?.step))?Number(raw.step):undefined,default:raw?.default??'',placeholder:String(raw?.placeholder||''),options:cleanOptions(raw?.options)}};
export function normalizeGameManifest(raw={}){const actions=(Array.isArray(raw.actions)?raw.actions:[]).map((a,i)=>({id:String(a?.id||`action${i+1}`),label:String(a?.label||a?.name||a?.id||`Ação ${i+1}`),description:String(a?.description||''),icon:String(a?.icon||'🎮'),iconImage:String(a?.iconImage||a?.image||''),params:(Array.isArray(a?.params)?a.params:[]).map(cleanField)})).filter(a=>a.id&&a.label);return{protocol:'liveplus-game-manifest-v1',gameId:String(raw.gameId||raw.id||'unknown-game'),name:String(raw.name||raw.gameName||'Jogo conectado'),icon:String(raw.icon||'🎮'),version:String(raw.version||''),actions};}

export class GameBridge extends EventTarget{
  constructor(){super();this.manifest=null;this.connected=false;this.onManifest=e=>this.setManifest(e.detail);this.onState=e=>{this.connected=true;this.dispatchEvent(new CustomEvent('state',{detail:e.detail}))};window.addEventListener('liveplus-game-manifest',this.onManifest);window.addEventListener('liveplus-game-state',this.onState);window.addEventListener('liveplus-game-disconnected',()=>{this.connected=false;this.manifest=null;this.dispatchEvent(new CustomEvent('disconnected'))})}
  setManifest(raw){this.manifest=normalizeGameManifest(raw||{});this.connected=true;this.dispatchEvent(new CustomEvent('manifest',{detail:this.manifest}));return this.manifest}
  getAction(id){return this.manifest?.actions?.find(a=>a.id===String(id))||null}
  send(rule,eventPayload){if(!rule?.actionId||!window.LivePlusMatch?.send)return false;return window.LivePlusMatch.send({type:'command',protocol:'liveplus-command-v1',gameId:rule.gameId||this.manifest?.gameId||'',action:rule.actionId,params:rule.actionParams||{},ruleId:rule.id,event:eventPayload||null,at:Date.now()})}
  mount(els){const section=els.rulesSection;if(!section||document.getElementById('gameActionBuilder'))return;const form=section.querySelector('.formGrid');if(!form)return;const wrap=document.createElement('div');wrap.id='gameActionBuilder';wrap.className='gameBuilder';wrap.innerHTML=`<div class="gameIdentity" id="gameIdentity"><div class="gameIdentityIcon">🎮</div><div><span>JOGO CONECTADO</span><strong>Aguardando jogo</strong><small>Conecte uma partida para descobrir as ações automaticamente.</small></div></div><label class="field" id="ruleActionField"><span>AÇÃO NO JOGO</span><select id="ruleAction"><option value="">Conecte um jogo primeiro</option></select></label><div id="ruleActionPreview" class="actionPreview" hidden></div><div id="ruleActionParams" class="actionParams"></div>`;form.insertAdjacentElement('afterend',wrap);}
  render(els,selectedAction='',params={}){const root=document.getElementById('gameActionBuilder');if(!root)return;const identity=document.getElementById('gameIdentity'),select=document.getElementById('ruleAction'),preview=document.getElementById('ruleActionPreview'),paramsRoot=document.getElementById('ruleActionParams');const m=this.manifest;if(!m){identity.innerHTML='<div class="gameIdentityIcon">🎮</div><div><span>JOGO CONECTADO</span><strong>Aguardando jogo</strong><small>Conecte uma partida para descobrir as ações automaticamente.</small></div>';select.innerHTML='<option value="">Conecte um jogo primeiro</option>';preview.hidden=true;paramsRoot.innerHTML='';return}identity.innerHTML=`<div class="gameIdentityIcon">${esc(m.icon)}</div><div><span>JOGO CONECTADO</span><strong>${esc(m.name)}</strong><small>${m.actions.length} ações disponíveis${m.version?` · v${esc(m.version)}`:''}</small></div>`;select.innerHTML='<option value="">Selecione uma ação</option>'+m.actions.map(a=>`<option value="${esc(a.id)}">${esc(a.icon)} ${esc(a.label)}</option>`).join('');if(selectedAction)select.value=selectedAction;this.renderAction(select.value,params)}
  renderAction(actionId,values={}){const preview=document.getElementById('ruleActionPreview'),root=document.getElementById('ruleActionParams'),action=this.getAction(actionId);if(!preview||!root)return;if(!action){preview.hidden=true;root.innerHTML='';return}preview.hidden=false;preview.innerHTML=`<div class="actionIcon">${action.iconImage?`<img src="${esc(action.iconImage)}" alt="">`:esc(action.icon)}</div><div><strong>${esc(action.label)}</strong><small>${esc(action.description||'Ação disponibilizada pelo jogo conectado')}</small></div>`;root.innerHTML=action.params.map(p=>{const value=values?.[p.id]??p.default??'';if(p.type==='select')return `<label class="field"><span>${esc(p.label)}</span><select data-action-param="${esc(p.id)}">${p.options.map(o=>`<option value="${esc(o.value)}" ${String(o.value)===String(value)?'selected':''}>${esc(o.label)}</option>`).join('')}</select></label>`;if(p.type==='toggle')return `<label class="paramToggle"><input type="checkbox" data-action-param="${esc(p.id)}" ${value===true||value==='true'?'checked':''}><span>${esc(p.label)}</span></label>`;return `<label class="field"><span>${esc(p.label)}</span><input data-action-param="${esc(p.id)}" type="${p.type==='number'?'number':'text'}" value="${esc(value)}" ${p.min!==undefined?`min="${p.min}"`:''} ${p.max!==undefined?`max="${p.max}"`:''} ${p.step!==undefined?`step="${p.step}"`:''} placeholder="${esc(p.placeholder)}"></label>`}).join('')}
  readParams(){const action=this.getAction(document.getElementById('ruleAction')?.value);if(!action)return{};const out={};for(const p of action.params){const el=document.querySelector(`[data-action-param="${CSS.escape(p.id)}"]`);if(!el)continue;out[p.id]=p.type==='toggle'?!!el.checked:p.type==='number'?(Number(el.value)||0):el.value}return out}
}
