(()=>{'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let manifest=null,lastState=null;
function ensureStyles(){if(document.getElementById('liveplusGameControlStyle'))return;const s=document.createElement('style');s.id='liveplusGameControlStyle';s.textContent=`
.gameControlPanel{margin-top:16px;border-top:1px solid rgba(255,255,255,.08);padding-top:16px}.gameControlHead{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;margin-bottom:12px}.gameControlHead h3{margin:3px 0 0;font-size:18px}.gameControlHead p{margin:5px 0 0;color:#8d96a8;font-size:11px;line-height:1.45}.gameControlBadge{padding:6px 9px;border:1px solid rgba(255,255,255,.12);border-radius:999px;font-size:9px;font-weight:900;white-space:nowrap}.gameControlGroups{display:grid;gap:12px}.gameControlGroup{border:1px solid rgba(255,255,255,.08);border-radius:14px;background:#080808;padding:11px}.gameControlGroup>strong{display:block;margin-bottom:9px;font-size:10px;letter-spacing:.08em;color:#aab3c4}.gameControlGrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:8px}.gameActionCard{border:1px solid rgba(255,255,255,.09);border-radius:12px;background:#0d0d0d;padding:10px}.gameActionTitle{display:flex;gap:8px;align-items:center;margin-bottom:4px}.gameActionIcon{font-size:17px}.gameActionTitle b{font-size:12px}.gameActionDesc{display:block;color:#7f899b;font-size:9px;line-height:1.4;min-height:25px}.gameActionParams{display:grid;gap:6px;margin:9px 0}.gameActionParams label{display:grid;gap:4px}.gameActionParams label>span{font-size:8px;font-weight:900;color:#8f9aab;letter-spacing:.06em}.gameActionParams input:not([type=checkbox]),.gameActionParams select{width:100%;min-width:0;padding:8px 9px;border:1px solid rgba(255,255,255,.12);border-radius:9px;background:#060606;color:#f5f5f5;font-size:11px}.gameActionParams .gameToggle{display:flex;grid-template-columns:none;align-items:center;gap:7px}.gameActionParams .gameToggle input{width:16px;height:16px}.gameActionRun{width:100%;padding:9px;border:1px solid rgba(255,255,255,.14);border-radius:9px;background:#151515;color:#fff;font-size:9px;font-weight:950;letter-spacing:.04em}.gameActionRun:active{transform:scale(.985)}.gameActionRun.sent{border-color:#2b8c67;color:#9ff2d0}.gameControlEmpty{padding:14px;border:1px dashed rgba(255,255,255,.12);border-radius:12px;color:#7f899b;font-size:10px;text-align:center}.gameControlState{margin-top:10px;padding:9px 10px;border-radius:10px;background:#070707;border:1px solid rgba(255,255,255,.07);font-size:9px;color:#929cad}.gameControlState.ok{color:#8ff0c7}.gameControlState.err{color:#ff9ca8}@media(max-width:620px){.gameControlGrid{grid-template-columns:1fr}.gameControlHead{align-items:center}}
`;document.head.appendChild(s)}
function ensureRoot(){ensureStyles();let root=document.getElementById('universalGameControl');if(root)return root;const section=document.getElementById('matchSection');if(!section)return null;root=document.createElement('div');root.id='universalGameControl';root.className='gameControlPanel';section.append(root);return root}
const groups={chaos:'CAOS / INIMIGOS',player:'JOGADOR / BENEFÍCIOS',admin:'CONTROLE DA PARTIDA',other:'OUTRAS AÇÕES'};
function normField(p,i){const type=['number','select','text','toggle'].includes(p?.type)?p.type:'text';return{id:String(p?.id||`param${i}`),label:String(p?.label||p?.name||p?.id||`Parâmetro ${i+1}`),type,default:p?.default??'',min:p?.min,max:p?.max,step:p?.step,options:Array.isArray(p?.options)?p.options:[]}}
function fieldHtml(p,i,actionId){const f=normField(p,i),id=`gc-${actionId}-${f.id}`.replace(/[^a-zA-Z0-9_-]/g,'_'),value=f.default;if(f.type==='select')return `<label><span>${esc(f.label)}</span><select id="${esc(id)}" data-gc-param="${esc(f.id)}" data-gc-type="select">${f.options.map(o=>{const v=typeof o==='string'?o:o?.value??o?.id??'',l=typeof o==='string'?o:o?.label??o?.name??v;return `<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${esc(l)}</option>`}).join('')}</select></label>`;if(f.type==='toggle')return `<label class="gameToggle"><input id="${esc(id)}" type="checkbox" data-gc-param="${esc(f.id)}" data-gc-type="toggle" ${value===true||value==='true'?'checked':''}><span>${esc(f.label)}</span></label>`;return `<label><span>${esc(f.label)}</span><input id="${esc(id)}" data-gc-param="${esc(f.id)}" data-gc-type="${esc(f.type)}" type="${f.type==='number'?'number':'text'}" value="${esc(value)}" ${f.min!==undefined?`min="${esc(f.min)}"`:''} ${f.max!==undefined?`max="${esc(f.max)}"`:''} ${f.step!==undefined?`step="${esc(f.step)}"`:''}></label>`}
function actionCard(a){const params=Array.isArray(a?.params)?a.params:[];return `<article class="gameActionCard" data-game-action="${esc(a.id)}"><div class="gameActionTitle"><span class="gameActionIcon">${esc(a.icon||'🎮')}</span><b>${esc(a.label||a.id)}</b></div><small class="gameActionDesc">${esc(a.description||'Ação disponibilizada pelo jogo conectado.')}</small><div class="gameActionParams">${params.map((p,i)=>fieldHtml(p,i,a.id)).join('')}</div><button class="gameActionRun" type="button" data-run-game-action="${esc(a.id)}">EXECUTAR</button></article>`}
function render(){const root=ensureRoot();if(!root)return;if(!manifest){root.innerHTML=`<div class="gameControlHead"><div><div class="kicker">CONTROLE UNIVERSAL</div><h3>Controle do jogo</h3><p>As opções administrativas aparecem automaticamente quando um jogo envia seu manifesto.</p></div><span class="gameControlBadge">SEM JOGO</span></div><div class="gameControlEmpty">Conecte um jogo pela sessão acima.</div>`;return}const actions=Array.isArray(manifest.actions)?manifest.actions:[],bucket={chaos:[],player:[],admin:[],other:[]};for(const a of actions){const key=['chaos','player','admin'].includes(a?.hudSide)?a.hudSide:'other';bucket[key].push(a)}root.innerHTML=`<div class="gameControlHead"><div><div class="kicker">CONTROLE UNIVERSAL · ${esc(manifest.name||'JOGO')}</div><h3>Painel do jogo</h3><p>${actions.length} comandos disponibilizados pelo próprio jogo. Estes controles não dependem de presente ou comentário.</p></div><span class="gameControlBadge">${esc(manifest.version?'v'+manifest.version:'CONECTADO')}</span></div><div class="gameControlGroups">${Object.entries(bucket).filter(([,list])=>list.length).map(([key,list])=>`<section class="gameControlGroup"><strong>${groups[key]}</strong><div class="gameControlGrid">${list.map(actionCard).join('')}</div></section>`).join('')}</div><div id="gameControlState" class="gameControlState">Jogo conectado · aguardando comando manual.</div>`}
function readParams(card){const out={};card.querySelectorAll('[data-gc-param]').forEach(el=>{const key=el.dataset.gcParam,type=el.dataset.gcType;if(type==='toggle')out[key]=!!el.checked;else if(type==='number')out[key]=Number(el.value)||0;else out[key]=el.value});return out}
function setStatus(text,kind=''){const el=document.getElementById('gameControlState');if(!el)return;el.textContent=text;el.className='gameControlState '+kind}
function run(actionId,button){if(!manifest?.gameId)return setStatus('Nenhum jogo conectado.','err');if(actionId==='restart'&&!confirm('Reiniciar a partida agora?'))return;const card=button.closest('.gameActionCard'),params=readParams(card);const ok=window.LivePlusMatch?.send?.({type:'command',protocol:'liveplus-command-v1',gameId:manifest.gameId,action:actionId,params,ruleId:'manual-admin',event:{type:'manual_control',user:'painel'},at:Date.now()});setStatus(ok?`Comando enviado · ${actionId}`:'Falha ao enviar · jogo desconectado',ok?'ok':'err');if(ok){button.classList.add('sent');const old=button.textContent;button.textContent='ENVIADO ✓';setTimeout(()=>{button.classList.remove('sent');button.textContent=old},900)}}
function init(){render();document.addEventListener('click',e=>{const b=e.target.closest('[data-run-game-action]');if(b)run(b.dataset.runGameAction,b)});window.addEventListener('liveplus-game-manifest',e=>{manifest=e.detail||null;render()});window.addEventListener('liveplus-game-state',e=>{lastState=e.detail||null;if(lastState?.scope==='command'&&lastState.commandStatus)setStatus(`Jogo: ${lastState.commandStatus} · ${lastState.action||''}`,lastState.commandStatus==='executed'?'ok':'')});window.addEventListener('liveplus-game-disconnected',()=>{manifest=null;render()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();