(()=>{'use strict';
const $=id=>document.getElementById(id);
let liveSince=0,timer=null,lastOn=false,lastPayload='',sessionStartedAt=0,sessionSerial=0;let gameConn=null;
function cleanUser(v=''){v=String(v||'').trim();if(!v)return '—';return '@'+v.replace(/^@/,'')}
function fmt(ms){const s=Math.max(0,Math.floor(ms/1000)),h=Math.floor(s/3600),m=Math.floor((s%3600)/60),x=s%60;return h?`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`}
function liveSnapshot(){const status=$('cloudStatus')?.textContent||'',badge=$('liveBadge')?.textContent||'',dot=$('cloudDot')?.textContent||'',input=$('cloudUser')?.value||'';const on=/TIKTOK LIVE CONECTADA/i.test(status)||(/LIVE CONECTADA/i.test(badge)&&/LIVE/i.test(dot));let user=input;const m=status.match(/@([^\s·]+)/);if(m)user=m[1];return{on,user:String(user||'').replace(/^@/,'').trim().slice(0,32),status,badge,dot}}
function beginFreshSession(){sessionStartedAt=Date.now();liveSince=sessionStartedAt;sessionSerial++;document.documentElement.dataset.caosLiveSession=String(sessionSerial);document.documentElement.dataset.caosLiveStartedAt=String(sessionStartedAt);try{sessionStorage.setItem('caos-live-session-started-at',String(sessionStartedAt))}catch{}resetStaleIndicators()}
function endSession(){liveSince=0;sessionStartedAt=0;try{sessionStorage.removeItem('caos-live-session-started-at')}catch{}}
function elapsedSec(){return sessionStartedAt?Math.max(0,Math.floor((Date.now()-sessionStartedAt)/1000)):0}
function resetStaleIndicators(){if(!sessionStartedAt)return;const elapsed=elapsedSec();document.querySelectorAll('body *').forEach(el=>{if(el.children.length)return;const text=(el.textContent||'').trim();let m=text.match(/sem\s+(?:evento|eventos|atividade)\s+(?:há|por)\s+(\d+)s/i);if(!m)m=text.match(/sem\s+eventos\s+por\s+(\d+)s/i);if(!m)return;const shown=+m[1]||0;if(shown>elapsed+5){el.textContent=text.replace(/\d+s/i,Math.max(0,elapsed)+'s')}})}
function hookPanelConnection(){if(typeof Peer==='undefined'||!Peer.prototype?.connect||Peer.prototype.connect.__caosLiveHook)return;const original=Peer.prototype.connect;function hooked(...args){const c=original.apply(this,args),target=String(args[0]||'');if(target.startsWith('chaos-live-')){gameConn=c;lastPayload='';c.on?.('open',()=>{gameConn=c;lastPayload='';sendGameLiveState(true)});c.on?.('close',()=>{if(gameConn===c)gameConn=null});c.on?.('error',()=>{if(gameConn===c&&!c.open)gameConn=null})}return c}hooked.__caosLiveHook=true;Peer.prototype.connect=hooked}
function ensure(){if($('tiktokLiveMonitor'))return;const anchor=document.querySelector('.automationsCard');if(!anchor)return;const el=document.createElement('section');el.id='tiktokLiveMonitor';el.className='card liveMonitorCard';el.innerHTML=`<div class="liveMonitorHead"><div><span class="eyebrow">TIKTOK LIVE</span><h2>Status da transmissão</h2></div><span id="liveMonitorBadge" class="liveMonitorBadge off"><i></i> LIVE OFF</span></div><div class="liveMonitorGrid"><div class="liveMonitorMain"><small>CONTA</small><b id="liveMonitorUser">—</b><span id="liveMonitorHint">Aguardando conexão com uma Live</span></div><div><small>DURAÇÃO</small><b id="liveMonitorTime">00:00</b></div><div><small>CURTIDAS</small><b id="liveMonitorLikes">0</b></div><div><small>CONNECTOR</small><b id="liveMonitorCloud">OFFLINE</b></div></div><div class="liveMonitorFoot"><span>ÚLTIMO EVENTO</span><b id="liveMonitorEvent">Nenhum evento recebido.</b></div>`;anchor.parentNode.insertBefore(el,anchor)}
function sendGameLiveState(force=false){if(!gameConn?.open)return false;const snap=liveSnapshot(),payload=JSON.stringify({liveStatus:snap.on?'on':'off',liveUser:snap.user});if(!force&&payload===lastPayload)return true;try{gameConn.send({type:'command',command:'ping',liveStatus:snap.on?'on':'off',liveUser:snap.user});lastPayload=payload;return true}catch{return false}}
function sync(){ensure();const snap=liveSnapshot(),on=snap.on,input=$('cloudUser')?.value||'';if(on&&!lastOn){lastOn=true;beginFreshSession()}if(!on&&lastOn){lastOn=false;endSession()}const b=$('liveMonitorBadge');if(b){b.className='liveMonitorBadge '+(on?'on':'off');b.innerHTML=`<i></i> ${on?'LIVE ON':'LIVE OFF'}`}if($('liveMonitorUser'))$('liveMonitorUser').textContent=on?cleanUser(snap.user):cleanUser(input);if($('liveMonitorHint'))$('liveMonitorHint').textContent=on?'Transmissão conectada e recebendo eventos':'Aguardando confirmação da TikTok Live';if($('liveMonitorLikes'))$('liveMonitorLikes').textContent=$('likeTotal')?.textContent||'0';if($('liveMonitorCloud')){$('liveMonitorCloud').textContent=/ONLINE|LIVE/i.test(snap.dot)?snap.dot:'OFFLINE';$('liveMonitorCloud').classList.toggle('ok',/ONLINE|LIVE/i.test(snap.dot))}if($('liveMonitorEvent'))$('liveMonitorEvent').textContent=$('liveStatus')?.textContent||'Nenhum evento recebido.';if($('liveMonitorTime'))$('liveMonitorTime').textContent=on&&liveSince?fmt(Date.now()-liveSince):'00:00';if(on)resetStaleIndicators();sendGameLiveState()}
function installRescueGuard(){const liveBtn=$('tiktokConnect');if(liveBtn&&!liveBtn.dataset.sessionGuard){liveBtn.dataset.sessionGuard='1';liveBtn.addEventListener('click',e=>{if(e.isTrusted)return;const snap=liveSnapshot();if(!snap.on||!sessionStartedAt)return;const age=Date.now()-sessionStartedAt;if(age<180000){e.preventDefault();e.stopImmediatePropagation();console.info('[Caos] auto-rescue bloqueado durante sessão recém-iniciada',Math.round(age/1000)+'s')}},true)}const stopBtn=$('tiktokDisconnect');if(stopBtn&&!stopBtn.dataset.sessionGuard){stopBtn.dataset.sessionGuard='1';stopBtn.addEventListener('click',e=>{if(e.isTrusted)return;const snap=liveSnapshot();if(!snap.on||!sessionStartedAt)return;const age=Date.now()-sessionStartedAt;if(age<180000){e.preventDefault();e.stopImmediatePropagation();console.info('[Caos] disconnect automático bloqueado durante sessão recém-iniciada',Math.round(age/1000)+'s')}},true)}}
function watch(){hookPanelConnection();ensure();installRescueGuard();document.getElementById('diagCard')?.remove();['cloudStatus','liveBadge','cloudDot','likeTotal','liveStatus'].forEach(id=>{const el=$(id);if(el)new MutationObserver(sync).observe(el,{childList:true,subtree:true,characterData:true,attributes:true})});$('cloudUser')?.addEventListener('input',sync);const bodyObserver=new MutationObserver(()=>{installRescueGuard();if(liveSnapshot().on)resetStaleIndicators()});bodyObserver.observe(document.body,{childList:true,subtree:true,characterData:true});timer=setInterval(()=>{sync();installRescueGuard();sendGameLiveState(true)},2000);sync()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watch);else watch();
})();