(()=>{'use strict';
const API={ready:false,name:'Snow Frost Puzzle',active:'snow-frost',seed:'ICE-BMFSXT',version:'',init:null,drawGround:null,drawObjects:null,resolveCollisions:null};
window.CaosMap=API;
const N=1,E=2,S=4,W=8,CHUNK=512,MAP_N=6,DENSITY=.85,VARIANT=.32,ORIGIN=-MAP_N*CHUNK/2;
let cfg=null,loading=false,manifest=null;
const byMask=Array.from({length:16},()=>[]),images=new Map(),grid=[];
function hashStr(s){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function H(x,y,s=0){let h=hashStr(API.seed);h^=Math.imul(x+0x9e3779b9,0x85ebca6b);h^=Math.imul(y+0xc2b2ae35,0x27d4eb2d);h^=s;h=Math.imul(h^(h>>>16),0x7feb352d);h=Math.imul(h^(h>>>15),0x846ca68b);return ((h^(h>>>16))>>>0)/4294967296}
function idx(x,y){return y*MAP_N+x}function inside(x,y){return x>=0&&y>=0&&x<MAP_N&&y<MAP_N}function cell(x,y){return inside(x,y)?grid[idx(x,y)]:null}
function chooseVariant(mask,x,y){const list=byMask[mask]||[];if(!list.length)return null;if(list.length===1)return list[0];return H(x,y,991)<VARIANT?(list.find(a=>a.variant===2)||list[1]||list[0]):(list.find(a=>a.variant===1)||list[0])}
function buildGrid(){grid.length=MAP_N*MAP_N;for(let y=0;y<MAP_N;y++)for(let x=0;x<MAP_N;x++){let m=0,up=cell(x,y-1),left=cell(x-1,y);if(up&&(up.mask&S))m|=N;if(left&&(left.mask&E))m|=W;if(x<MAP_N-1&&H(x,y,101)<DENSITY)m|=E;if(y<MAP_N-1&&H(x,y,102)<DENSITY)m|=S;grid[idx(x,y)]={mask:m,def:chooseVariant(m,x,y)}}}
function loadImage(def){return new Promise(resolve=>{const im=new Image();im.onload=()=>{images.set(def.id,im);resolve(true)};im.onerror=()=>resolve(false);im.src='./assets/Map/snow-frost/'+def.file+'?v='+String(API.version||'map').replace(/\./g,'')})}
async function load(){if(loading)return;loading=true;try{const r=await fetch('./assets/Map/snow-frost/manifest.json?v='+String(API.version||'map').replace(/\./g,''),{cache:'no-store'});if(!r.ok)throw Error('manifest '+r.status);manifest=await r.json();for(const a of byMask)a.length=0;for(const d of manifest.chunks||[])if(Number.isInteger(d.mask)&&d.mask>=0&&d.mask<=15)byMask[d.mask].push(d);buildGrid();const allDefs=(manifest.chunks||[]).slice(),defs=cfg?.lite?[...new Map([...grid.map(c=>c?.def),...(byMask[0]||[])].filter(Boolean).map(d=>[d.id,d])).values()]:allDefs,ok=await Promise.all(defs.map(loadImage));API.ready=allDefs.length===32&&ok.filter(Boolean).length===defs.length&&grid.every(c=>c?.def);console.log('CAOS MAP SNOW FROST PUZZLE READY',{ready:API.ready,seed:API.seed,chunks:defs.length,grid:MAP_N+'x'+MAP_N})}catch(e){API.ready=false;console.warn('CAOS MAP SNOW FROST FALLBACK',e)}finally{loading=false}}
API.init=o=>{cfg=o;API.version=String(o?.version||'');load()};
function closedDef(cx,cy){const list=byMask[0]||[];if(!list.length)return null;return H(cx,cy,1991)<.5?(list.find(a=>a.variant===2)||list[1]||list[0]):(list.find(a=>a.variant===1)||list[0])}
function chunkDef(cx,cy){return inside(cx,cy)?cell(cx,cy)?.def:closedDef(cx,cy)}
function chunkWorld(cx,cy){return{x:ORIGIN+cx*CHUNK,y:ORIGIN+cy*CHUNK}}
API.drawGround=()=>{if(!API.ready||!cfg)return false;const {ctx}=cfg,p=cfg.player(),v=cfg.viewport(),minX=Math.floor((p.x-v.W/2-CHUNK-ORIGIN)/CHUNK),maxX=Math.ceil((p.x+v.W/2+CHUNK-ORIGIN)/CHUNK),minY=Math.floor((p.y-v.H/2-CHUNK-ORIGIN)/CHUNK),maxY=Math.ceil((p.y+v.H/2+CHUNK-ORIGIN)/CHUNK);ctx.fillStyle='#d8e8ef';ctx.fillRect(0,0,v.W,v.H);ctx.save();ctx.imageSmoothingEnabled=!cfg?.lite;for(let cy=minY;cy<=maxY;cy++)for(let cx=minX;cx<=maxX;cx++){const def=chunkDef(cx,cy),im=def&&images.get(def.id);if(!im)continue;const w=chunkWorld(cx,cy),q=cfg.world(w.x,w.y);ctx.drawImage(im,q.x-1,q.y-1,CHUNK+2,CHUNK+2)}ctx.restore();if(!cfg?.lite){ctx.fillStyle='rgba(110,170,196,.055)';ctx.fillRect(0,0,v.W,v.H);const g=ctx.createRadialGradient(v.W/2,v.H/2,100,v.W/2,v.H/2,Math.max(v.W,v.H)*.78);g.addColorStop(0,'rgba(230,248,255,0)');g.addColorStop(1,'rgba(33,73,94,.14)');ctx.fillStyle=g;ctx.fillRect(0,0,v.W,v.H)}return true};
API.drawObjects=()=>{};
function resolveCircle(t,r,cx,cy,cr,slide,key){let dx=t.x-cx,dy=t.y-cy,d=Math.hypot(dx,dy),min=r+cr;if(d>=min)return;if(d<.001){const a=H(key,Math.floor(cy),1777)*Math.PI*2;dx=Math.cos(a);dy=Math.sin(a);d=1}const ux=dx/d,uy=dy/d,overlap=Math.min(28,min-d+.6);t.x+=ux*overlap;t.y+=uy*overlap;if(slide){const side=H(key,Math.floor(cx),1778)>.5?1:-1;t.x+=-uy*overlap*.16*side;t.y+=ux*overlap*.16*side}}
function nearbyCollisionDefs(p=cfg.player()){const baseX=Math.floor((p.x-ORIGIN)/CHUNK),baseY=Math.floor((p.y-ORIGIN)/CHUNK),out=[];for(let cy=baseY-2;cy<=baseY+2;cy++)for(let cx=baseX-2;cx<=baseX+2;cx++){const def=chunkDef(cx,cy);if(!def||!Array.isArray(def.collision)||!def.collision.length)continue;const w=chunkWorld(cx,cy);for(const c of def.collision){if(c.type!=='circle')continue;out.push({x:w.x+c.x*CHUNK,y:w.y+c.y*CHUNK,r:c.r*CHUNK,key:cx*97+cy*131})}}return out}
API.resolveCollisions=()=>{if(!API.ready||!cfg)return;const p=cfg.player(),cs=nearbyCollisionDefs(p);for(const c of cs)resolveCircle(p,p.r||18,c.x,c.y,c.r,false,c.key);for(const q of (cfg.extraPlayers?.()||[])){if(!q||q.down)continue;const qs=nearbyCollisionDefs(q);for(const c of qs)resolveCircle(q,q.r||18,c.x,c.y,c.r,false,c.key)}for(const e of cfg.enemies()){if(e.dead)continue;for(const c of cs)resolveCircle(e,e.r||16,c.x,c.y,c.r,true,c.key)}};
})();
