(()=>{'use strict';
function cleanCode(value=''){const s=String(value).toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,8);return s.length===8?s.slice(0,4)+'-'+s.slice(4):s}
function relayEndpoint(){try{return String(window.LivePlusServerRelay?.endpoint?.()||'').trim()}catch{return''}}
function relayState(){try{return window.LivePlusServerRelay?.state?.()||null}catch{return null}}
function makeTicket(code){const c=cleanCode(code);if(c.length!==9)return c;const relay=relayEndpoint();if(!relay)return c;return'LIVEPLUS1|'+c+'|'+encodeURIComponent(relay)}
function normalIcon(){return'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="8" y="8" width="11" height="11" rx="2"></rect><rect x="5" y="5" width="11" height="11" rx="2"></rect></svg>'}
function transportLabel(){const s=relayState();if(!s)return'';if(s.mode==='peer'||!s.endpoint)return'WEBRTC ONLINE';if(s.game)return'SERVIDOR + WEBRTC';if(s.ready)return'SERVIDOR AGUARDANDO';if(s.socket==='connecting'||s.socket==='authenticating')return'SERVIDOR CONECTANDO';if(s.socket==='auth-error')return'WEBRTC · CHAVE INVÁLIDA';return'WEBRTC FALLBACK'}
function syncTransportRole(){const s=relayState(),transport=document.getElementById('matchTransport'),primary=document.getElementById('matchRelayPrimary'),backup=document.getElementById('matchRelayBackup');if(!s)return;const text=transportLabel();if(transport&&text&&transport.textContent!==text)transport.textContent=text;if(primary){let value='PRINCIPAL · WEBRTC';if(s.mode!=='peer'&&s.endpoint)value=s.game?'PAREAMENTO · SERVIDOR ONLINE':s.ready?'PAREAMENTO · SERVIDOR AGUARDANDO':s.socket==='connecting'||s.socket==='authenticating'?'PAREAMENTO · SERVIDOR CONECTANDO':'PAREAMENTO · SERVIDOR + FALLBACK';if(primary.textContent!==value)primary.textContent=value}if(backup){const value=s.mode==='peer'?'SEM SERVIDOR · CONEXÃO ANTIGA':s.endpoint?'COMANDOS · WEBRTC PREFERENCIAL':'SERVIDOR OPCIONAL · NÃO CONFIGURADO';if(backup.textContent!==value)backup.textContent=value}}
async function copyTicket(event){const button=event.currentTarget;try{window.LivePlusServerRelay?.create?.()}catch{}const text=makeTicket(window.LivePlusMatch?.getCode?.()||'');if(!text)return;event.preventDefault();event.stopImmediatePropagation();let ok=false;try{await navigator.clipboard.writeText(text);ok=true}catch{}if(!ok){try{const ta=document.createElement('textarea');ta.value=text;ta.readOnly=true;ta.style.position='fixed';ta.style.opacity='0';document.body.append(ta);ta.select();ok=document.execCommand('copy');ta.remove()}catch{}}if(!ok)return;button.classList.add('copied');button.innerHTML='<span aria-hidden="true">✓</span>';button.setAttribute('aria-label','Código copiado');setTimeout(()=>{button.classList.remove('copied');button.innerHTML=normalIcon();button.setAttribute('aria-label','Copiar código da partida')},1600)}
function provision(){const endpoint=relayEndpoint();if(!endpoint)return false;try{return!!window.LivePlusMatch?.send?.({type:'relay_config',protocol:'liveplus-relay-config-v1',endpoint,version:1,at:Date.now()})}catch{return false}}
function install(){const button=document.getElementById('copyMatchCode');if(button&&!button.dataset.ticketReady){button.dataset.ticketReady='1';button.addEventListener('click',copyTicket,true)}syncTransportRole();const transport=document.getElementById('matchTransport');if(transport&&!transport.dataset.transportOwner){transport.dataset.transportOwner='ticket';new MutationObserver(syncTransportRole).observe(transport,{childList:true,characterData:true,subtree:true})}}
window.addEventListener('load',install);window.addEventListener('pageshow',install);window.addEventListener('liveplus-relay-ready',syncTransportRole);window.addEventListener('liveplus-game-manifest',()=>{install();syncTransportRole();setTimeout(provision,0)});window.addEventListener('liveplus-game-disconnected',syncTransportRole);window.addEventListener('online',syncTransportRole);setInterval(syncTransportRole,750);
window.LivePlusTicket={make:makeTicket,provision,syncTransportRole};
})();