(()=>{'use strict';
const $=id=>document.getElementById(id);
const WORDS=['uva','banana','maçã','laranja','mamão','melancia','morango','abacaxi','limão','manga','vinho','suco','fruta','comida','arroz','feijão','pizza','pão','queijo','café','leite','ovo','carro','moto','avião','barco','casa','porta','janela','mesa','cadeira','cama','sofá','telefone','computador','livro','caneta','bola','camisa','sapato','cachorro','gato','cavalo','leão','tigre','elefante','macaco','peixe','pássaro','árvore','flor','praia','rio','montanha','chuva','sol','lua','estrela','fogo','água','terra','amor','feliz','rápido','grande','pequeno'];
const NAMES=['teste_01','teste_02','player_teste','ghost_teste','live_tester','qa_player'];
let timer=null,sent=0,target=0,lastIndex=-1;
function installStyle(){if($('matchTestStyle'))return;const s=document.createElement('style');s.id='matchTestStyle';s.textContent=`.matchTestBox{margin-top:18px;border:1px solid #31505c;border-radius:20px;padding:16px;background:#071820;display:grid;gap:13px}.matchTestHead{display:flex;justify-content:space-between;align-items:flex-start;gap:12px}.matchTestHead span{display:block;color:#78909a;font-size:8px;font-weight:950;letter-spacing:.13em}.matchTestHead strong{display:block;margin-top:4px;font-size:16px}.matchTestHead small{display:block;margin-top:5px;color:#7f959e;line-height:1.45}.matchTestPill{border:1px solid #31505c;border-radius:999px;padding:8px 10px;font-size:9px;font-weight:950;color:#9ff3e6;white-space:nowrap}.matchTestGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.matchTestGrid label{display:grid;gap:6px}.matchTestGrid span{font-size:8px;font-weight:950;letter-spacing:.1em;color:#78909a}.matchTestGrid input,.matchTestGrid select,.matchTestManual input{width:100%;min-width:0}.matchTestActions,.matchTestManual{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.matchTestStatus{border:1px solid #26424e;border-radius:13px;padding:10px 12px;font-size:10px;color:#8397a0;background:#06151d}.matchTestStatus.ok{color:#65dfad}.matchTestStatus.running{color:#9ff3e6;border-color:#2e706d}.matchTestStatus.error{color:#ff8b98;border-color:#713743}.matchTestLog{display:grid;gap:6px}.matchTestLogItem{border-left:3px solid #2d5961;border-radius:10px;padding:9px 11px;background:#06151d;color:#879ba4;font-size:9px}.matchTestLogItem.ok{border-left-color:#50d69c}.matchTestLogItem.error{border-left-color:#ff7c8a}@media(max-width:760px){.matchTestHead{flex-direction:column}.matchTestGrid,.matchTestActions,.matchTestManual{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function ensureUI(){if($('matchTestBox'))return true;const host=$('matchSection');if(!host)return false;installStyle();const box=document.createElement('div');box.id='matchTestBox';box.className='matchTestBox';box.innerHTML=`<div class="matchTestHead"><div><span>TESTE DA PARTIDA · ISOLADO DOS COMANDOS</span><strong>Simulador de comentários</strong><small>Envia palpites falsos diretamente ao jogo conectado. Não cria regra, comando ou doação.</small></div><div class="matchTestPill"><b id="matchTestSent">0</b> ENVIADOS</div></div><div class="matchTestGrid"><label><span>QUANTIDADE</span><input id="matchTestCount" type="number" min="1" max="500" value="50"></label><label><span>INTERVALO</span><select id="matchTestInterval"><option value="1000">1 por segundo</option><option value="500" selected>2 por segundo</option><option value="250">4 por segundo</option><option value="100">10 por segundo</option></select></label></div><div class="matchTestActions"><button id="startMatchTest" class="primary" type="button">INICIAR PALAVRAS ALEATÓRIAS</button><button id="stopMatchTest" class="danger" type="button" disabled>PARAR TESTE</button></div><div class="matchTestManual"><input id="matchTestWord" autocomplete="off" placeholder="Palavra manual, ex.: banana"><button id="sendMatchTestWord" type="button">ENVIAR PALAVRA</button></div><div id="matchTestStatus" class="matchTestStatus">Pronto para simular comentários.</div><div id="matchTestLog" class="matchTestLog"></div>`;host.appendChild(box);return true}
function status(text,kind=''){const el=$('matchTestStatus');if(!el)return;el.textContent=text;el.className='matchTestStatus '+kind}
function log(text,tone=''){const out=$('matchTestLog');if(!out)return;const row=document.createElement('div');row.className='matchTestLogItem '+tone;row.textContent=new Date().toLocaleTimeString('pt-BR')+' · '+text;out.prepend(row);while(out.children.length>6)out.lastChild.remove()}
function randomWord(){if(WORDS.length<2)return WORDS[0]||'teste';let i;do{i=Math.floor(Math.random()*WORDS.length)}while(i===lastIndex);lastIndex=i;return WORDS[i]}
function randomName(){return NAMES[Math.floor(Math.random()*NAMES.length)]+'_'+String(Math.floor(Math.random()*90)+10)}
function payload(word,username=randomName()){return{type:'comment',event:'comment',eventType:'comment',protocol:'liveplus-test-comment-v1',source:'match-simulator',simulated:true,username,nickname:username,comment:word,text:word,message:word,at:Date.now(),messageId:'test-'+Date.now()+'-'+Math.random().toString(36).slice(2,8)}}
function sendWord(word,{quiet=false}={}){word=String(word||'').trim();if(!word)return false;const ok=!!window.LivePlusMatch?.send?.(payload(word));if(ok){sent++;if($('matchTestSent'))$('matchTestSent').textContent=String(sent);if(!quiet)log(`Comentário de teste · “${word}”`,'ok');status(`Enviado ao jogo · ${sent} comentário${sent===1?'':'s'}`,'ok')}else{status('Nenhum jogo conectado à Partida.','error');if(!quiet)log('Envio recusado · conecte um jogo primeiro.','error')}return ok}
function stop(reason='Teste parado.'){clearInterval(timer);timer=null;target=0;if($('startMatchTest'))$('startMatchTest').disabled=false;if($('stopMatchTest'))$('stopMatchTest').disabled=true;status(reason,'')}
function start(){if(timer)return;const count=Math.max(1,Math.min(500,Number($('matchTestCount')?.value)||50));const interval=Math.max(100,Math.min(5000,Number($('matchTestInterval')?.value)||500));sent=0;target=count;if($('matchTestSent'))$('matchTestSent').textContent='0';if(!sendWord(randomWord(),{quiet:true})){sent=0;if($('matchTestSent'))$('matchTestSent').textContent='0';status('Conecte um jogo antes de iniciar o teste.','error');log('Teste não iniciado · sem jogo conectado.','error');return}if($('startMatchTest'))$('startMatchTest').disabled=true;if($('stopMatchTest'))$('stopMatchTest').disabled=false;status(`Teste rodando · ${sent}/${target}`,'running');log(`Teste iniciado · ${target} comentários · ${interval} ms`,'ok');if(sent>=target){stop(`Teste concluído · ${sent} comentário enviado.`);return}timer=setInterval(()=>{if(sent>=target){stop(`Teste concluído · ${sent} comentários enviados.`);log('Sequência automática concluída.','ok');return}if(!sendWord(randomWord(),{quiet:true})){stop('Teste interrompido · jogo desconectado.');return}status(`Teste rodando · ${sent}/${target}`,'running')},interval)}
function init(){if(!ensureUI())return;const startBtn=$('startMatchTest');if(startBtn.dataset.ready)return;startBtn.dataset.ready='1';startBtn.addEventListener('click',start);$('stopMatchTest')?.addEventListener('click',()=>stop('Teste parado pelo painel.'));$('sendMatchTestWord')?.addEventListener('click',()=>{const input=$('matchTestWord');if(sendWord(input?.value||'')){if(input)input.value=''}});$('matchTestWord')?.addEventListener('keydown',e=>{if(e.key==='Enter')$('sendMatchTestWord')?.click()});window.addEventListener('liveplus-game-disconnected',()=>{if(timer)stop('Teste interrompido · jogo desconectado.')});status('Pronto para simular comentários.','')}
if(document.readyState==='loading')window.addEventListener('load',init);else init();
window.LivePlusMatchTest={start,stop,send:sendWord,isRunning:()=>!!timer};
})();